### ISSUE TITLE
Docs broken?

### ISSUE THREAD

**Issue by surfjedi** [infamous/infamous#1]
Just tried to look a the docs for this but it appears that only the menu works? no content?

**Comment by trusktr** [comment]
@surfjedi Hi, that's because there are no docs. When you looked, the project was brand new, but we've since then decided to go in a new direction: instead of working with and maintaining a fork of Famous Engine, we decided to start our own engine. We're planning and discussing over at forums.infamous.io (the site was updated to link to there).

We're got 5 prototypes in the community, and sooner than later we want to merge ideas into a single repo for the library.

Prototypes with working demos:
http://github.com/infamous/famin (demos: gadi.cc/famin)
http://github.com/infamous/motor/tree/andrewreedy (demo: hybrid-developer.meteor.com)
http://github.com/dmvaldman/samsara (demo: samsarajs.org)

Prototypes not yet rendering, but will soon:
http://github.com/infamous/boxer
http://github.com/infamous/motor/tree/joe

**Comment by trusktr** [comment]
@surfjedi Finally, I started the docs page on http://infamous.io... more coming very soon...
