### ISSUE TITLE
motor-html: Allow extension of existing elements, making it easy to integrate 3D into any existing HTML app.

### ISSUE THREAD

**Issue by ghost** [infamous/infamous#5]
(Not sure if this is feasible yet)

For example, suppose we take on a new project, and the new project has some existing HTML in it:

```js
<div>
  <div id="foo">
    <h1>Hello</h1>
  </div>
</div>
```

Can we make an API so that we can enhance the app by applying the `is=""` attributes to the elements in order to introduce the 3D engine, by for example changing the markup to:

```js
<div is="motor-scene" ...>
  <div id="foo" is="motor-node" ...>
    <h1>Hello</h1>
  </div>
</div>
```

If we can do that, then we can apply things to those elements like rotation, translate, animation, etc:

```js
let node =  $('#foo')
let r = 0
requestAnimationFrame(function animation() {
  node.attr('rotation', `0, ${r++}, 0`)
  requestAnimationFrame(animation)
})
```

**Comment by trusktr** [comment]
After re-evaluating the current Custom Element API, I don't think this is feasible due to how the `is=""` attribute works. The API doesn't allow for an arbitrary element type to be extended without a pre-made definition, which means in order to let the user be able to extend different elements (div, button, p, etc) we'd have to make a definition for each and every element.

It'd be nice if the API allowed for Custom Element definitions to extend whichever element they are applied to at runtime.

Closing unless this changes.
